
version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  aws-s3: circleci/aws-s3@3.1.1
  

jobs:
  # Decode the tfvars environment variable and save to workspace
  deploy_backend:
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo $AWS_CLOUDRESUME_TERRAFORMTFVARS_FILE | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: Cpy tfvars file to project directory
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          var_file: terraform.tfvars
          path: .
      - terraform/apply:
          var_file: terraform.tfvars
          path: .
      - aws-s3/copy:
          from: website/
          to: s3://$(terraform output -raw website_bucket_name)
workflows:
  test-deploy:
    jobs:
      - deploy_backend:
          context:
            - terraform
      
      
    
