
version: '2.1'

jobs:
  # Decode the tfvars environment variable and save to workspace
  deploy_terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    # executor: terraform/default
    steps:
      - checkout
      # Install AWS CLI (optional if not already installed in your base image)
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          command: >-
            echo $AWS_CLOUDRESUME_TERRAFORMTFVARS_FILE | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: Cpy tfvars file to project directory
      - run:
          name: terraform validate, init & plan 
          command: |
            terraform validate
            terraform init 
            terraform plan -out -var-file terraform.tfvars
      - run:
          name: terraform apply
          command: |
            terraform apply -var-file terraform.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          command: >-
            aws s3 cp website/ s3://$(terraform output -raw website_bucket_name)/ --recursive
          name: Cpy tfvars file to project directory
  


workflows:
  test-deploy:
    jobs:
      - deploy_terraform:
          context:
            - terraform

