
version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  aws-s3: circleci/aws-s3@3.1.1
  

jobs:
  # Decode the tfvars environment variable and save to workspace
  deploy_backend:
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo $AWS_CLOUDRESUME_TERRAFORMTFVARS_FILE | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: Cpy tfvars file to project directory
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          var_file: terraform.tfvars
          path: .
      - terraform/apply:
          var_file: terraform.tfvars
          path: .
      - run:
          name: Get S3 Bucket Name
          command: |
            # Get the S3 bucket name from Terraform output and store it in the BUCKET_NAME variable
            BUCKET_NAME=$(terraform output -raw website_bucket_name)
            echo "S3 Bucket Name: $BUCKET_NAME"
            echo "BUCKET_NAME=$BUCKET_NAME" >> $BASH_ENV
      - aws-s3/copy:
          from: website/
          to: "s3://${BUCKET_NAME}/"


workflows:
  test-deploy:
    jobs:
      - deploy_backend:
          context:
            - terraform
      
      
    
