
version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@4.0.0

jobs:

  deploy_terraform:
    executor: terraform/default
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    steps:
      - checkout
      # Decode the tfvars environment variable and save to workspace
      - run:
          command: >-
            echo $AWS_CLOUDRESUME_TERRAFORMTFVARS_FILE | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: Cpy tfvars file to project directory
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          var_file: terraform.tfvars
          path: .
          out: "terraform.tfplan"
      - terraform/apply:
          var_file: terraform.tfvars
          path: .
      # Save the Terraform plan output to a workspace
      - persist_to_workspace:
          root: .
          paths:
            - "terraform.tfplan"
  awss3copy:
    executor: aws-cli/default
    steps:
      - checkout
      # Restore the Terraform plan output and AWS credentials from the workspace
      - attach_workspace:
          at: .
       - aws-s3/copy:
          arguments: '--recursive'
          from: website/
          install-aws-cli: false
          to: s3://eacheampong.work

  


workflows:
  test-deploy:
    jobs:
      - deploy_terraform:
          context:
            - terraform
      - awss3copy:
          context:
            - terraform
          requires:
            - deploy_terraform

