
version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.1
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  deploy_terraform:
    executor: terraform/default
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    steps:
      - checkout
      # Decode the tfvars environment variable and save to workspace
      - run:
          command: >-
            echo $AWS_CLOUDRESUME_TERRAFORMTFVARS_FILE | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: Cpy tfvars file to project directory
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          var_file: terraform.tfvars
          path: .
          out: "terraform.tfplan"
      - terraform/apply:
          var_file: terraform.tfvars
          path: .
      # Save the Terraform plan output to a workspace
      - persist_to_workspace:
          root: .
          paths:
            - "terraform.tfplan"
  awss3copy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: >-
              ls -la          
          name: List files and folders
          context: terraform
      - aws-s3/copy:
          arguments: '--recursive'
          from: website/
          install-aws-cli: false
          to: s3://eacheampong.work
 


workflows:
  test-deploy:
    jobs:
      - deploy_terraform:
          context:
            - terraform
      - awss3copy:
          context:
            - terraform
          requires:
            - deploy_terraform

