
version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@4.0.0  


jobs:
  # Decode the tfvars environment variable and save to workspace
  deploy_terraform:
    executor: terraform/default
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    # executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo $AWS_CLOUDRESUME_TERRAFORMTFVARS_FILE | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: Cpy tfvars file to project directory
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          var_file: terraform.tfvars
          path: .
          out: "terraform.tfplan"
       # Extract the value of 'website_bucket_name' output and set it as an environment variable
      - run:
          name: Set environment variable
          command: echo "WEBSITE_BUCKET_NAME=$(terraform show -json terraform.tfstate | jq -r '.values.root_module.resources[] | select(.address == \"aws_s3_bucket.website\") | .values.bucket')" >> $BASH_ENV
          environment:
            BASH_ENV: $BASH_ENV
      - terraform/apply:
          var_file: terraform.tfvars
          path: .
      # Save the Terraform plan output to a workspace
      - persist_to_workspace:
          root: .
          paths:
            - "terraform.tfplan"
  awss3copy:
    executor: aws-cli/default
    steps:
      - checkout
      # Restore the Terraform plan output and AWS credentials from the workspace
      - attach_workspace:
          at: .
      - run:
          command: aws s3 cp website/ s3://WEBSITE_BUCKET_NAME)/ --recursive

  


workflows:
  test-deploy:
    jobs:
      - deploy_terraform:
          context:
            - terraform
      - awss3copy:
          context:
            - terraform
          requires:
            - deploy_terraform

