
version: '2.1'
orbs:
  terraform: circleci/terraform@3.1  

jobs:
  # Decode the tfvars environment variable and save to workspace
  deploy_terraform:
    docker:
      - image: circleci/python:3.8
    environment:
      CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}"
    # executor: terraform/default
    steps:
      - checkout
      # Install AWS CLI (optional if not already installed in your base image)
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          command: >-
            echo $AWS_CLOUDRESUME_TERRAFORMTFVARS_FILE | base64 -d > $HOME/terraform.tfvars
          name: Create terraform.tfvars variable file
          context: terraform
      - run:
          command: >-
            cp $HOME/terraform.tfvars .
          name: Cpy tfvars file to project directory
      - terraform/validate:
          path: .
      - terraform/init:
          path: .
      - terraform/plan:
          var_file: terraform.tfvars
          path: .
      - terraform/apply:
          var_file: terraform.tfvars
          path: .
      - run:
          command: >-
            aws s3 cp website/ s3://$(terraform output -raw website_bucket_name)/ --recursive
          name: Cpy tfvars file to project directory
  


workflows:
  test-deploy:
    jobs:
      - deploy_terraform:
          context:
            - terraform

